### PR TITLE
Basic layout

### LINKED ISSUE #3: Basic CRUD page and hook for the page
- Implement CRUD operation for user and prepare test script for that

### LINKED ISSUE #4: Basic layout
- Pick react UI component library
- Add layout for authentication, and the main app with navigation

### PR DESCRIPTION
**Pull request by nikolasvasconcelos**
**Basic Layout implementation**

- [x] Material UI Library
- [x] Theme configuration
- [x] Basic Navigator Implementation
- [x] Jest unit tests

### CODE REVIEW

**Comment by JonghunYu** [comment]
@nikolasvasconcelos Could you add some descriptions on what this PR is about?

**Comment by nikolasvasconcelos** [comment]
@JonghunYu please ignore this review request, I forgot the navigation part

**Comment by nikolasvasconcelos** [comment]
@JonghunYu now it's ready for review

**Review by JonghunYu — APPROVED** [review]
@nikolasvasconcelos it looks good to me

**Pull request merged**
